### ISSUE TITLE
otsu threshold value

### ISSUE THREAD

**Issue by dschneiderch** [Computational-Plant-Science/DIRT#4]
Hi @koalaspirit  - Someone asked me for help segmenting roots in DIRT. I was looking through the source to understand the segmentation and, if I understand correctly, the global otsu threshold value is being used as the standard deviation (sigma) for the local gaussian filter, and then the mask is created with an offset of -20.
What's the basis for using the global otsu value as sigma? I assume the -20 offset  resulted from trial and error?

**Comment by koalaspirit** [comment]
Hi @dschneiderch - the images that we use have often not a clear threshold because they are taken in the field with sometimes adverse lighting conditions. In that case, you don't have a clear cutoff value because your histogram of intensity values is not bimodal (needed for otsu to work properly), but rather a mixture of many more distributions.  The otsu value is then either over- or underestimated depending on the intensity distribution. Since we don't know at that point how much the value is away from the real otsu threshold we can use it to determine sigma. If the image is good then the otsu threshold will be small e.g. 10. Hence, the Gaussian filter is narrow and intensity changes in the surrounding of a pixel have not much influence during the adaptive treshold. If the image has bad lighting conditions, the otsu threshold gets larger, e.g. 60, and Gaussian filter becomes wider such that intensity differences in the surrounding of a pixel get more influence during the adaptive thresholding. The offset of -20 simply suppresses noise in the low-intensity pixel values because the resulting negative values are treated as zeros. I hope this helps.

**Comment by dschneiderch** [comment]
Thanks! I'll have to try this with chl fluorescence images.

**Comment by koalaspirit** [comment]
Hey @dschneiderch . If it does not work, then just drop me an email. We have other segmentations that we use for fluorescence images. I'm happy to bring you in contact with a postdoc in my lab that developed it.

Cheers,
Alex

**Comment by dschneiderch** [comment]
I’d be interested either way! Currently I rely on entropy based methods like Yen which work surprisingly well even with a little algae.

**Comment by koalaspirit** [comment]
@dschneiderch you can contact @lsx1980 (Suxing Liu) about segmentation.
